# Generated by Django 3.2.5 on 2021-08-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0002_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبدهای خرید کاربران'},
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(verbose_name='پرداخت شده / نشده'),
        ),
    ]
